// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get Supabase credentials from environment variables
// Fallback to default values for development (these should be in .env in production)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://qprxkdvabdsziplssogb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwcnhrZHZhYmRzemlwbHNzb2diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjEzOTcsImV4cCI6MjA3MzE5NzM5N30.3Ahqd_1IcIJ681vkF4F7sjWniytdf6TaOb_6ltkx4uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Add headers for CORS
  global: {
    headers: {
      'apikey': SUPABASE_PUBLISHABLE_KEY,
    },
  },
});

// Test connection on load (only log errors)
if (typeof window !== 'undefined') {
  console.log('🔧 Testing Supabase connection...');
  supabase.from('users').select('count').limit(0).then(({ error }) => {
    if (error) {
      console.error('❌ Supabase connection failed:', error.code, error.message);
      if (error.code === 'PGRST301' || error.message?.includes('permission')) {
        console.error('⚠️ This is likely an RLS policy issue. Run fix_supabase_rls.sql in Supabase.');
      }
    } else {
      console.log('✅ Supabase connection successful');
    }
  }).catch(err => {
    console.error('❌ Supabase connection error:', err);
  });
}