// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// SECURITY FIX: Remove hardcoded credentials - require environment variables
// This prevents credential exposure in source code and enables proper rotation
// For development and production, provide fallback values if .env is not configured
// This prevents white screen of death if env vars are missing
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://qprxkdvabdsziplssogb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwcnhrZHZhYmRzemlwbHNzb2diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjEzOTcsImV4cCI6MjA3MzE5NzM5N30.3Ahqd_1IcIJ681vkF4F7sjWniytdf6TaOb_6ltkx4uo";

// Warn if using fallback values (but don't crash the app)
if (!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_ANON_KEY) {
  const missing = [];
  if (!import.meta.env.VITE_SUPABASE_URL) missing.push('VITE_SUPABASE_URL');
  if (!import.meta.env.VITE_SUPABASE_ANON_KEY) missing.push('VITE_SUPABASE_ANON_KEY');
  
  console.warn(
    `⚠️ Missing Supabase environment variables: ${missing.join(', ')}\n` +
    `Using fallback values. Please set these in your Vercel environment variables for production.\n` +
    `Go to: Vercel Dashboard → Your Project → Settings → Environment Variables`
  );
  
  // In production, also log to console.error for visibility
  if (import.meta.env.PROD) {
    console.error(
      `🚨 PRODUCTION: Missing Supabase environment variables!\n` +
      `The app will work with fallback values, but this is not recommended.\n` +
      `Please add ${missing.join(' and ')} to Vercel environment variables.`
    );
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Add headers for CORS
  global: {
    headers: {
      'apikey': SUPABASE_PUBLISHABLE_KEY,
    },
  },
});

// Test connection on load (only log errors)
if (typeof window !== 'undefined') {
  console.log('🔧 Testing Supabase connection...');
  supabase.from('users').select('count').limit(0).then(({ error }) => {
    if (error) {
      console.error('❌ Supabase connection failed:', error.code, error.message);
      if (error.code === 'PGRST301' || error.message?.includes('permission')) {
        console.error('⚠️ This is likely an RLS policy issue. Run fix_supabase_rls.sql in Supabase.');
      }
    } else {
      console.log('✅ Supabase connection successful');
    }
  }).catch(err => {
    console.error('❌ Supabase connection error:', err);
  });
}